### ISSUE TITLE
docs: Add Issue Templates

### ISSUE THREAD

**Issue by maityamit** [hash-define-organization/hashdefine-onlineIDE#13]
Chnages
Adding Issue templates
Template path  ``` .github/ISSUE_TEMPLATE ``` 
**Template Types**

![156198784-b2e8d551-3df4-4aff-a7c7-051a88c344c0](https://user-images.githubusercontent.com/74618071/156574710-6e75dbde-7ee9-4cb7-9297-c516d5092eb8.png)
![156169861-53b91128-a1aa-4751-805e-affb8a4924a3](https://user-images.githubusercontent.com/74618071/156574718-869a8c87-a672-4d4a-a32e-61e60fb0c6bc.png)

Contribution towards GSsoc`22, Thank you

**Comment by maityamit** [comment]
I want to work in this issue under GSSoC'22 .
Please assign me .

**Comment by VaibhavPaliwal0007** [comment]
okay issue assigned !!

**Comment by maityamit** [comment]
@VaibhavPaliwal0007 Thanks 🙂
