### ISSUE TITLE
Login/Signup endpoint(Backend).

### ISSUE THREAD

**Issue by ayush25102001** [hash-define-organization/hashdefine-onlineIDE#15]
Sir, I will create an API endpoint for login/Signup of the users.
Here the details of the user will be taken in accordance to the User schema created, during signing up those details will be stored in the database(locally for now).
Then, when the user logs in he will be checked (i.e the username and password he earlier gave match the once given now).

Wishing to work on this as a participant under Gssoc'22.

**Comment by irshadmd** [comment]
Go ahead 🚀

**Comment by VaibhavPaliwal0007** [comment]
okay can you also add google authentication in it like users can sign up/ sign in through google.

**Comment by irshadmd** [comment]
Login with Google and Github both
@VaibhavPaliwal0007 what do you think?

**Comment by VaibhavPaliwal0007** [comment]
sounds cool

**Comment by irshadmd** [comment]
@ayush25102001 please integrate login with google and github options as well.

**Comment by ayush25102001** [comment]
@irshadmd ,
Sorry sir, Actually I am new to this so for now can I just create those endpoints at the backend??
Later when I learn about google auth I will implement that in.

**Comment by irshadmd** [comment]
that's not very complex you can google it and if you face any issue let me know

**Comment by thedreader** [comment]
I would like to also work on this issue.

**Comment by ayush25102001** [comment]
Ok sir, I will try!!

**Comment by irshadmd** [comment]
> I would like to also work on this issue.

you can work with @ayush25102001

**Comment by Karan11000** [comment]
I want to work on this issue under GSSoC 2022. Can you assign it to me

**Comment by irshadmd** [comment]
> I want to work on this issue under GSSoC 2022. Can you assign it to me

you can add login with Google and Github

**Comment by irshadmd** [comment]
@Karan11000 create another issue explaining what you will be doing since this issue is already assigned.
