### ISSUE TITLE
Feature: To add a download code button

### ISSUE THREAD

**Issue by aparna-bhatt** [hash-define-organization/hashdefine-onlineIDE#18]
### Feature description

Hey, I wanted to suggest if we could add a download code button that would be nice.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by aparna-bhatt** [comment]
Also I am a gssoc participant if you could assign this issue under gssoc.

**Comment by VaibhavPaliwal0007** [comment]
Okay that would be great!

**Comment by aparna-bhatt** [comment]
I am done with functionality.I just 
wanted to know the styling of the button. So I am attaching the screenshot. Please see to it.
![Screenshot (103)](https://user-images.githubusercontent.com/86338542/156896159-3bf20bd6-b4d1-4250-8355-f99ce2536728.png)

**Comment by irshadmd** [comment]
use download icon only like
![downloadcode](https://user-images.githubusercontent.com/32608381/156896596-5a0bb79d-b63b-4801-8848-8faf5493ce00.png)

**Comment by aparna-bhatt** [comment]
ok!

**Comment by aparna-bhatt** [comment]
![icon](https://user-images.githubusercontent.com/86338542/156933758-540b0ce5-c1d0-4980-9f25-99fa1e53c5e2.png)
this looks fine?

**Comment by khareyash05** [comment]
Make it a bit bigger as well and also add a subtitle for the same 'Download source code'

**Comment by aparna-bhatt** [comment]
Hey I am facing some problem in merging can you help me with it.

**Comment by irshadmd** [comment]
> Hey I am facing some problem in merging can you help me with it.

check deploy logs
