### ISSUE TITLE
Documentation: There is some mistake in readme.

### ISSUE THREAD

**Issue by aparna-bhatt** [hash-define-organization/hashdefine-onlineIDE#19]
### Description

In the readme to add upstream, it is written git remote add but it should be git remote add upstream 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by VaibhavPaliwal0007** [comment]
okay assigned!

**Comment by aparna-bhatt** [comment]
I have made a pull request please see to it.
