### ISSUE TITLE
Tab for Memory Consumed Missing

### ISSUE THREAD

**Issue by WINOFFRG** [hash-define-organization/hashdefine-onlineIDE#2]
👋 After checking the Response received from the compiler, An extra parameter **"memory"** (Memory Consumed) is there. It would be great to use it by adding an Extra tab showing the memory consumed by the Program. 

References attached below 👇
![image](https://user-images.githubusercontent.com/61311751/112130747-cfd12680-8bee-11eb-9a7f-44459f7f5bd0.png)

**Comment by saxenapeeyush** [comment]
cool then add it.
