### ISSUE TITLE
Feature: Add more Editor layouts

### ISSUE THREAD

**Issue by Tusharjagi** [hash-define-organization/hashdefine-onlineIDE#23]
### Feature description

Hey I'm Tushar, I want to contribute in your project .

- I wish i could add a more a ***Editor layout***  option in IDE .

I'm participant in GSSoC22.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by irshadmd** [comment]
great idea, please share the layouts before starting implementation.

**Comment by Tusharjagi** [comment]
First thing i do,  i will add the setting option in nav section in which we select the editor layout .
For now i only add a Tabs layout feature like (chrome tabs). 
In future i would add more layout option .

**Comment by Tusharjagi** [comment]
Can you please reassign me by mistake i was removed our assignment. Sorry !!!!

**Comment by irshadmd** [comment]
> First thing i do, i will add the setting option in nav section in which we select the editor layout . For now i only add a Tabs layout feature like (chrome tabs). In future i would add more layout option .

looks good🚀

**Comment by khareyash05** [comment]
@Tusharjagi Any updates??

**Comment by Tusharjagi** [comment]
Yeah I knew little of react, i stuck in between I am trying to solve it, can you give me time till 10 april.

**Comment by irshadmd** [comment]
> Yeah I knew little of react, i stuck in between I am trying to solve it, can you give me time till 10 april.

It's been 28 days already, please try to finish fast otherwise it will be assigned to someone else.

**Comment by Tusharjagi** [comment]
Okay
