### ISSUE TITLE
Documentation: Contribution File addition

### ISSUE THREAD

**Issue by vish-han** [hash-define-organization/hashdefine-onlineIDE#24]
### Description

There is no contribution.md file present in the documentations of the project . It will help the beginner who is contributing to the project for the first time to understand the core of git and how contributions is made.

@VaibhavPaliwal0007 can you assign me for this issue.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by VaibhavPaliwal0007** [comment]
okay assigned!!

**Comment by khareyash05** [comment]
@vish-han Are working on this?
Last date - 5th April 2022

**Comment by vish-han** [comment]
No I have my exams, you can contribute if u want to
