### ISSUE TITLE
Feature:  Enhancing run button

### ISSUE THREAD

**Issue by Pd-1204** [hash-define-organization/hashdefine-onlineIDE#26]
### Feature description

Enhancing the run button . Just an arrow wouldn't be appropriate.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by irshadmd** [comment]
Go ahead 🚀

**Comment by irshadmd** [comment]
@Pd-1204 are you working on this issue?

**Comment by Pd-1204** [comment]
No. it's done.
