### ISSUE TITLE
Feature: Delete/Update routes

### ISSUE THREAD

**Issue by ayush25102001** [hash-define-organization/hashdefine-onlineIDE#29]
### Feature description

Adding delete route such that the user can delete his profile info this would be done only if the username and password credentials match.
Adding update route such that user can update is profile, eg: A user learns a new language then it can be added.
I would like to work on the backend part as a participant under gssoc’22.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by irshadmd** [comment]
will think about it in future.
