### ISSUE TITLE
Variable Name Change

### ISSUE THREAD

**Issue by HarshitX1002** [hash-define-organization/hashdefine-onlineIDE#33]
### Description

 It is some change in variable name in terminal.js file where it is mentioned about subTerminal for both input terminal and output terminal, My proposed change would be very simple like subTerminalInput and subTerminalOutput. Plus I would also like to add comments in this project files for clear usage of it
![Screenshot 2022-03-13 134419](https://user-images.githubusercontent.com/53402059/158101701-fd9ba896-a4db-43a1-8556-60a19cf8c6a7.png)
.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by HarshitX1002** [comment]
I would like to work on this issue. It would be great, if assigned to me.

**Comment by irshadmd** [comment]
go ahead🚀

**Comment by irshadmd** [comment]
Merged pr #36
