### ISSUE TITLE
Title LOGO and Name

### ISSUE THREAD

**Issue by vish-han** [hash-define-organization/hashdefine-onlineIDE#4]
@VaibhavPaliwal0007 
The name and logo of the website is still the default one , 
I would like to make the change if you can assign me😊✌️

**Comment by VaibhavPaliwal0007** [comment]
Yes assigning to you!!

**Comment by VaibhavPaliwal0007** [comment]
![define new glasses glare logo](https://user-images.githubusercontent.com/78612380/156581190-852d6352-987c-4997-a59a-09b2a62c1a22.svg)
You can take this logo for website favicon @vish-han

**Comment by vish-han** [comment]
Okk I will make PR soon,  I'm completing my end sem assignment now 😅

**Comment by jyotivakare33** [comment]
Hi Can i take up the issue if this is still pending.

**Comment by vish-han** [comment]
The PR for this project is already merged😄
