### ISSUE TITLE
Login/signUp buttons

### ISSUE THREAD

**Issue by ayush25102001** [hash-define-organization/hashdefine-onlineIDE#42]
### Feature description

I would create the login and signUp button.
Also would create the form for login and signUp (React Component).

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by khareyash05** [comment]
Go ahead @ayush25102001

**Comment by khareyash05** [comment]
@ayush25102001 ANy updates??

**Comment by ayush25102001** [comment]
> @ayush25102001 ANy updates??

Can I just Add the button as I am not able to add model part

**Comment by irshadmd** [comment]
@khareyash05 he is not able to complete this issue let someone else do it
