### ISSUE TITLE
[Bug]: Light theme isn't working for input/output area.

### ISSUE THREAD

**Issue by Siddhesh777** [hash-define-organization/hashdefine-onlineIDE#47]
### Contact Details

jainsiddhesh777@gmail.com

### What happened?

if we enable a light theme then background and font color is not changing for input-ouput area.

![1](https://user-images.githubusercontent.com/77476772/161308684-d1f8c935-d2a9-45ef-9393-8ca6651c65df.png)

I am contributor at GSSOC'22.
Please assign this task to me.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by khareyash05** [comment]
Go ahead!

**Comment by khareyash05** [comment]
I am sorry.Duplicate #21
