### ISSUE TITLE
Feature: Add a whiteboard.

### ISSUE THREAD

**Issue by dasgupta002** [hash-define-organization/hashdefine-onlineIDE#49]
### Feature description

A whiteboard aside the editor for doing easy board work needed for problem solving.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

As a participant of GSSOC '22, I myself would like to work on this issue.
Hope to get assigned this one in a whirl!

**Comment by khareyash05** [comment]
Go ahead!
