### ISSUE TITLE
Feature: CRUD operation

### ISSUE THREAD

**Issue by ayush25102001** [hash-define-organization/hashdefine-onlineIDE#59]
### Feature description

I will setup all the CRUD operations for the user where changes will also reflect in the database.
Operations like update/read/delete will work only with authentication.
 I wish to work on the backend part.
Participant under Gssoc’22 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by khareyash05** [comment]
Go ahead!

**Comment by TG922** [comment]
Is someone working on this issue??
