### ISSUE TITLE
Adding Login and Signup button

### ISSUE THREAD

**Issue by TG922** [hash-define-organization/hashdefine-onlineIDE#65]
### Feature description

- I would like to create the Login and Signup button 
- Creating the form for Login and Signup using React Component
 
### Code of Conduct
* [x]  I agree to follow this project's Code of Conduct

**Comment by irshadmd** [comment]
go ahead 🚀

**Comment by khareyash05** [comment]
@TG922  @irshadmd There is already a same issue #42

**Comment by irshadmd** [comment]
@TG922 please work on it
