### ISSUE TITLE
User(Model)

### ISSUE THREAD

**Issue by ayush25102001** [hash-define-organization/hashdefine-onlineIDE#7]
Can I make the model for User(Backend) which will have fields like username, password, college, language preferences.
Participant under gssoc’22

**Comment by VaibhavPaliwal0007** [comment]
in which framework?

**Comment by ayush25102001** [comment]
NodeJs(Javascript)
MongoDB(Database)

**Comment by VaibhavPaliwal0007** [comment]
ok assigned
