### ISSUE TITLE
Feature: Code Copy to Clipboard Button

### ISSUE THREAD

**Issue by raghavpatidar** [hash-define-organization/hashdefine-onlineIDE#70]
### Feature description

Add a Button to copy code to clipboard near download code button .

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by irshadmd** [comment]
Go ahead🚀

**Comment by raghavpatidar** [comment]
I have added the copy button but i PR is not getting all checks clear
