### ISSUE TITLE
responsiveness 

### ISSUE THREAD

**Issue by VaibhavPaliwal0007** [hash-define-organization/hashdefine-onlineIDE#9]
the website is not responsive in mobile

**Comment by Ardent10** [comment]
Can I do this?

**Comment by Ardent10** [comment]
> Yes, you can, do share the full-screen recording in various ratios. Assigning to you.

Here are the changes:  #22

**Comment by thefstalphabet** [comment]
Hey, I would like to work on this issue, under GSSoC'22. Can you please assign it to me?

**Comment by irshadmd** [comment]
> Hey, I would like to work on this issue, under GSSoC'22. Can you please assign it to me?
Hey @thefstalphabet create a new issue.
